# Generated by Django 4.1 on 2022-09-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='This is a description', max_length=400),
        ),
    ]
